import perfectionist from 'eslint-plugin-perfectionist'
import { defineConfig } from 'oxlint'

export default defineConfig({
	categories: {
		correctness: 'off',
	},
	env: {
		builtin: true,
		node: true,
	},
	ignorePatterns: [
		'**/node_modules/**',
		'**/.next/**',
		'**/.vercel/**',
		'**/build/**',
		'**/dist/**',
		'**/out/**',
		'**/coverage/**',
		'**/generated/**',
		'**/messages.js',
		'extension/**',
		'playwright-report/**',
		'test-results/**',
		'.claude/**',
		'.codex/**',
		'.agents/**',
		'next-env.d.ts',
	],
	jsPlugins: ['eslint-plugin-perfectionist'],
	overrides: [
		{
			env: {
				browser: true,
				node: true,
			},
			files: ['**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
			plugins: ['import', 'jsx-a11y', 'nextjs', 'react', 'typescript'],
			rules: {
				'import/no-anonymous-default-export': 'warn',
				'jsx-a11y/alt-text': [
					'warn',
					{
						elements: ['img'],
						img: ['Image'],
					},
				],
				'jsx-a11y/aria-props': 'warn',
				'jsx-a11y/aria-proptypes': 'warn',
				'jsx-a11y/aria-unsupported-elements': 'warn',
				'jsx-a11y/role-has-required-aria-props': 'warn',
				'jsx-a11y/role-supports-aria-props': 'warn',
				'nextjs/google-font-display': 'warn',
				'nextjs/google-font-preconnect': 'warn',
				'nextjs/inline-script-id': 'error',
				'nextjs/next-script-for-ga': 'warn',
				'nextjs/no-assign-module-variable': 'error',
				'nextjs/no-async-client-component': 'warn',
				'nextjs/no-before-interactive-script-outside-document': 'warn',
				'nextjs/no-css-tags': 'warn',
				'nextjs/no-document-import-in-page': 'error',
				'nextjs/no-duplicate-head': 'error',
				'nextjs/no-head-element': 'warn',
				'nextjs/no-head-import-in-document': 'error',
				'nextjs/no-html-link-for-pages': 'error',
				'nextjs/no-img-element': 'warn',
				'nextjs/no-page-custom-font': 'warn',
				'nextjs/no-script-component-in-head': 'error',
				'nextjs/no-styled-jsx-in-document': 'warn',
				'nextjs/no-sync-scripts': 'error',
				'nextjs/no-title-in-document-head': 'warn',
				'nextjs/no-typos': 'warn',
				'nextjs/no-unwanted-polyfillio': 'warn',
				'react/display-name': 'error',
				'react/error-boundaries': 'error',
				'react/exhaustive-deps': 'warn',
				'react/globals': 'error',
				'react/immutability': 'error',
				'react/incompatible-library': 'warn',
				'react/jsx-key': 'error',
				'react/jsx-no-comment-textnodes': 'error',
				'react/jsx-no-duplicate-props': 'error',
				'react/jsx-no-target-blank': 'off',
				'react/jsx-no-undef': 'error',
				'react/no-children-prop': 'error',
				'react/no-danger-with-children': 'error',
				'react/no-direct-mutation-state': 'error',
				'react/no-find-dom-node': 'error',
				'react/no-is-mounted': 'error',
				'react/no-render-return-value': 'error',
				'react/no-string-refs': 'error',
				'react/no-unescaped-entities': 'error',
				'react/no-unknown-property': 'off',
				'react/no-unsafe': 'off',
				'react/preserve-manual-memoization': 'error',
				'react/purity': 'error',
				'react/react-in-jsx-scope': 'off',
				'react/refs': 'error',
				'react/require-render-return': 'error',
				'react/rules-of-hooks': 'error',
				'react/set-state-in-effect': 'error',
				'react/set-state-in-render': 'error',
				'react/static-components': 'error',
				'react/unsupported-syntax': 'warn',
				'react/use-memo': 'error',
			},
		},
		{
			files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
			rules: {
				'constructor-super': 'off',
				'getter-return': 'off',
				'no-class-assign': 'off',
				'no-const-assign': 'off',
				'no-dupe-class-members': 'off',
				'no-dupe-keys': 'off',
				'no-func-assign': 'off',
				'no-import-assign': 'off',
				'no-new-native-nonconstructor': 'off',
				'no-obj-calls': 'off',
				'no-redeclare': 'off',
				'no-setter-return': 'off',
				'no-this-before-super': 'off',
				'no-unreachable': 'off',
				'no-unsafe-negation': 'off',
				'no-var': 'error',
				'no-with': 'off',
				'prefer-const': 'error',
				'prefer-rest-params': 'error',
				'prefer-spread': 'error',
			},
		},
	],
	plugins: ['typescript'],
	rules: {
		...perfectionist.configs['recommended-natural'].rules,
		'no-array-constructor': 'error',
		'no-unused-expressions': 'warn',
		'no-unused-vars': [
			'warn',
			{
				args: 'all',
				argsIgnorePattern: '^_',
				caughtErrors: 'all',
				caughtErrorsIgnorePattern: '^_',
				destructuredArrayIgnorePattern: '^_',
				varsIgnorePattern: '^_',
			},
		],
		'typescript/ban-ts-comment': 'error',
		'typescript/no-duplicate-enum-values': 'error',
		'typescript/no-empty-object-type': 'error',
		'typescript/no-explicit-any': 'error',
		'typescript/no-extra-non-null-assertion': 'error',
		'typescript/no-misused-new': 'error',
		'typescript/no-namespace': 'error',
		'typescript/no-non-null-asserted-optional-chain': 'error',
		'typescript/no-require-imports': 'error',
		'typescript/no-this-alias': 'error',
		'typescript/no-unnecessary-type-constraint': 'error',
		'typescript/no-unsafe-declaration-merging': 'error',
		'typescript/no-unsafe-function-type': 'error',
		'typescript/no-wrapper-object-types': 'error',
		'typescript/prefer-as-const': 'error',
		'typescript/prefer-namespace-keyword': 'error',
		'typescript/triple-slash-reference': 'error',
	},
	settings: {
		next: {
			rootDir: ['.'],
		},
	},
})
