export const AIR_QUALITY_AQI_DEFAULT_MAX = 150
export const PRECIPITATION_CHART_DEFAULT_MAX_MM = 5
export const UV_CHART_DEFAULT_MAX = 15
export const VISIBILITY_CHART_DEFAULT_MAX_METERS = 10_000
export const WIND_CHART_DEFAULT_MAX_KMH = 40
