name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build

  release-check:
    name: Release Validation
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.event.head_commit.message, '(release)') || (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '(release)'))
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate package.json version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "Release version: $VERSION"
          
          # Check if version follows semantic versioning
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must follow semantic versioning (x.y.z)"
            exit 1
          fi

      - name: Check if tag already exists
        run: |
          VERSION=$(jq -r .version package.json)
          if git ls-remote --tags origin | grep -q "refs/tags/v${VERSION}$"; then
            echo "Error: Tag v${VERSION} already exists"
            exit 1
          fi

      - name: Additional release tests
        run: |
          echo "Running additional release validation..."
          # Add any additional release-specific tests here
          pnpm test
          echo "All release tests passed!"

  security-check:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

  all-checks:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [test, security-check]
    if: always()
    
    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            echo "Tests failed"
            exit 1
          fi
          
          if [[ "${{ needs.security-check.result }}" != "success" ]]; then
            echo "Security check failed"
            exit 1
          fi
          
          echo "All checks passed!"